version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11  # Use an appropriate Python version
    
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python manage.py test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build